version: '3.4'

volumes:
  cache:
  log:
  vendor:

services:
  app:
    ports:
      - 5500:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    build:
      context: .
    volumes:
      # - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./var/cache:/var/www/html/var/cache
      - ./var/log:/var/www/html/var/log
      - vendor:/var/www/html/vendor